# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "Juliette Murris - personal website"
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of the site
url: "https://juliettemurris.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""
remote_theme: eliottvincent/bay

header:
  pages:
    - name: Publications
      slug: /publications
    - name: Talks & events
      slug: /talks
    - name: Teaching & supervision
      slug: /teaching
    - name: Other
      slug: /other

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: lastname[dot]firstname[at]gmail.com
      link: mailto:murris.juliette@gmail.com
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/juliettemurris
    - name: GitHub
      link: http://github.com/juliettemurris
    - name: ORCID
      link: https://orcid.org/0000-0002-7017-9865
    - name: RGate
      link: https://www.researchgate.net/profile/Juliette-Murris?ev=hdr_xprf
    - name: GScholar
      link: https://scholar.google.com/citations?user=pLBeL6AAAAAJ&hl=fr

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
